name: rescuelink
description: RescueLink disaster rescue communication application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  nearby_connections: ^4.3.0
  permission_handler: ^10.4.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^14.0.2
  vosk_flutter: ^0.3.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/vosk-model-small-en-us-0.15.zip

dependency_overrides:
  permission_handler: ^11.3.1
  permission_handler_android: ^12.0.13