name: rescuelink_pec_01
description: RescueLink App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true